/** Page titles that describe how to use a guide, not a capability. */
export const STRUCTURAL_TITLE = [
  /^what is\b/i, /^getting started/i, /^set(ting)? up\b/i, /^tutorial/i, /^quotas?\b/i,
  /^service quotas/i, /^pricing/i, /^cost/i, /^document history/i, /^doc history/i,
  /^troubleshoot/i, /^glossary/i, /^release notes/i, /^api reference/i, /^cli\b/i,
  /^sdk\b/i, /^code examples?/i, /^examples?$/i, /^concepts/i, /^how .* works$/i,
  /^prerequisites/i, /^accessing\b/i, /^overview$/i, /^introduction$/i, /^welcome/i,
  /^tagging\b/i, /^tag your/i, /^working with the console/i, /^best practices$/i,
  /^related information/i, /^additional resources/i, /^faq/i, /^limitations/i,
  /^supported\b/i, /^regions and endpoints/i, /^availability\b/i, /^contributors$/i, /^appendix/i,
  /^resources$/i, /^security$/i, /^compliance validation$/i, /^resilience$/i,
  /^infrastructure security$/i, /^data protection$/i, /^identity and access management$/i,
  /^logging and monitoring$/i, /^configuration and vulnerability analysis$/i,
  /^cross-service confused deputy prevention$/i, /^update management$/i,
  /^security best practices$/i, /^monitoring\b/i, /^using the aws cli/i, /^using aws sdk/i,
  // Policy examples, walkthrough steps and integration notes are documentation, not capability.
  /^[A-Za-z0-9]+:\s/,
  /^sample code/i,
  /^examples? (of|for)\b/i,
  /\bworks with (iam|aws)\b/i,
  /^step \d/i,
  /^(view|list|create|delete|update|edit|modify|add|remove|assign|deactivate|resynchronize|recover|check|generate|download|upload|import|export|copy|move|untag|enable|disable|start|stop|turn)\b/i,
  /^migrating\b/i, /^what's new/i,
];

/**
 * Named security controls. These names identify a real capability wherever they
 * appear, which is how tier 2 features are found inside non-security guides.
 */
export const NAMED_CONTROL = [
  /\bblock(ing)?\s+(all\s+)?public access\b/i,
  /\bpublic access block\b/i,
  /\bpublic access settings?\b/i,
  /\bobject lock\b/i,
  /\bvault lock\b/i,
  /\bservice control polic/i,
  /\bresource control polic/i,
  /\bdeclarative polic/i,
  /\btag polic/i,
  /\bbackup polic/i,
  /\bchat applications polic/i,
  /\bai services opt-out polic/i,
  /\bsecurity hub polic/i,
  /\bauth polic/i,
  /\bbucket polic/i,
  /\bkey polic/i,
  /\btrust polic/i,
  /\bpermissions? boundar/i,
  /\bsession polic/i,
  /\bscp\b/i,
  /\bsecurity group/i,
  /\bnetwork acl/i,
  /\bnetwork access control list/i,
  /\binstance metadata service/i,
  /\bimdsv2\b/i,
  /\bnitro enclave/i,
  /\bkey pair/i,
  /\ballowed amis?\b/i,
  /\bebs encryption\b/i,
  /\bencryption by default\b/i,
  /\bdefault (bucket )?encryption\b/i,
  /\bserver-side encryption\b/i,
  /\bclient-side encryption\b/i,
  /\bdual-layer server-side encryption\b/i,
  /\bcustomer-provided encryption keys?\b/i,
  /\bbucket keys?\b/i,
  /\benvelope encryption\b/i,
  /\bkey rotation\b/i,
  /\bmulti-region keys?\b/i,
  /\bcustom key store\b/i,
  /\bexternal key store\b/i,
  /\bhmac keys?\b/i,
  /\basymmetric keys?\b/i,
  /\bcustomer managed keys?\b/i,
  /\bgrants?\b/i,
  /\baccess grants?\b/i,
  /\baccess points?\b/i,
  /\bimage scanning\b/i,
  /\baccess control\b/i,
  /\bbucket ownership\b/i,
  /\bownership controls?\b/i,
  /\bencrypting\b/i,
  /\bblocking\b/i,
  /\bvulnerability scanning\b/i,
  /\bmalware (protection|scanning)\b/i,
  /\bruntime monitoring\b/i,
  /\bthreat detection\b/i,
  /\bcode signing\b/i,
  /\bcode security\b/i,
  /\bsbom\b/i,
  /\bsoftware bill of materials\b/i,
  /\bcis scan/i,
  /\bpatch manager\b/i,
  /\bsession manager\b/i,
  /\bparameter store\b/i,
  /\bsecurestring\b/i,
  /\bdns firewall\b/i,
  /\btls inspection\b/i,
  /\bstateful rule/i,
  /\bstateless rule/i,
  /\bdomain list/i,
  /\bweb acl/i,
  /\bmanaged rule (group|set)/i,
  /\brate-based rule/i,
  /\bbot control\b/i,
  /\bfraud control\b/i,
  /\baccount takeover prevention\b/i,
  /\bcaptcha\b/i,
  /\bchallenge\b.*\bwaf\b/i,
  /\bshield advanced\b/i,
  /\bddos\b/i,
  /\bproactive engagement\b/i,
  /\bhealth-based detection\b/i,
  /\bmulti-factor authentication\b/i,
  /\bmfa\b/i,
  /\bservice-linked role/i,
  /\bcredential report/i,
  /\baccess keys?\b/i,
  /\broot (user )?(access|credential)/i,
  /\bconformance pack/i,
  /\bconfig rule/i,
  /\bremediation\b/i,
  /\baggregator\b/i,
  /\bevent data store/i,
  /\bcloudtrail lake\b/i,
  /\binsights? events?\b/i,
  /\bdata events?\b/i,
  /\bmanagement events?\b/i,
  /\bnetwork activity events?\b/i,
  /\borganization trail/i,
  /\bautomation rule/i,
  /\bsecurity standard/i,
  /\bsecurity control/i,
  /\bcontrol polic/i,
  /\bbehavior graph\b/i,
  /\bsubscriber\b/i,
  /\bcertificate transparency\b/i,
  /\bcertificate authorit/i,
  /\brotation\b/i,
  /\badvanced security\b/i,
  /\bthreat protection\b/i,
  /\btrust provider/i,
  /\bidentity provider/i,
  /\bsaml\b/i,
  /\boidc\b/i,
  /\bopenid connect\b/i,
  /\bfederation\b/i,
  /\bexternal access\b/i,
  /\binternal access\b/i,
  /\bunused access\b/i,
  /\bpolicy validation\b/i,
  /\bpolicy generation\b/i,
  /\bcustom policy check/i,
  /\bmanaged data identifier/i,
  /\bcustom data identifier/i,
  /\ballow list/i,
  /\bsensitive data discovery\b/i,
  /\bautomated (sensitive data )?discovery\b/i,
  /\bfindings? aggregation\b/i,
  /\bdelegated administrator\b/i,
  /\bprotection plan\b/i,
  /\bprotection$/i,
  /\bexposure findings?\b/i,
  /\battack path\b/i,
  /\bguardrail/i,
  /\bcontrol tower control/i,
  /\bproactive control/i,
  /\bdetective control/i,
  /\bpreventive control/i,
  /\bprivatelink\b/i,
  /\bvpc endpoint polic/i,
  /\binterface endpoint\b/i,
  /\bpost-quantum\b/i,
  /\bfips\b/i,
  /\bencryption context\b/i,
  /\bsecrets? rotation\b/i,
  /\bcredential\b/i,
  /\bpassword polic/i,
  /\bpassthrough\b.*\bauth/i,
];

/** Container chapters whose children are the real features. */
export const CONTAINER_SECTION = [
  /^protection plans?$/i,
  /^features?$/i,
  /^capabilit/i,
  /^security$/i,
  /^organization polic/i,
  /^policies$/i,
  /^controls?$/i,
  /^scan types?$/i,
  /^data protection$/i,
  /^identity and access management$/i,
];

export function isStructural(title: string): boolean {
  return STRUCTURAL_TITLE.some((p) => p.test(title.trim()));
}

export function matchesNamedControl(text: string): RegExp | undefined {
  return NAMED_CONTROL.find((p) => p.test(text));
}

export function isContainer(title: string): boolean {
  return CONTAINER_SECTION.some((p) => p.test(title.trim()));
}
